<?php
/**
 * Parent Form UI class
 */
class FormUI {
  /**
   * Container for the items in this form.
   *
   * @var array
   */
  public $items = array();

  /**
   * The current item weight, if we're autosetting it.
   *
   * @var mixed
   */
  public $weight = NULL;

  /**
   * Weight increment.
   *
   * @var int
   */
  public $weightIncrement = 10;

  /**
   * Create the form
   */
  public function __construct($form = array()) {
    $this->items = $form;
  }

  /**
   * Handle calling for items.
   *
   * You can call $form->[type]() to generate a form
   */
  public function __call($method, $arguments) {
    $class_name = 'FormUI' . ucfirst($method);
    if (class_exists($class_name)) {
      $instance = new $class_name();
      $instance->setOptions($arguments);
      return $instance;
    }
    throw new Exception('Method or form item does not exist: ' . $class_name);
  }

  /**
   * Add an item.
   *
   * This can be used in one of three ways:
   *
   * 1. Add a FormUIItem:
   *
   *     $item = new FormUIMarkup('<p>markup</p>');
   *     $form_ui->add('key', $item);
   *
   * 2. Use a FormUIItem generator:
   *
   *     $form_ui->add('key', $form_ui->markup('<p>markup</p>'));
   *
   * 3. For markup, you can use a shortcut:
   *
   *     $form_ui->add('key', '<p>markup</p>');
   */
  public function add($key, $item) {
    $args = func_get_args();
    $arg_count = count($args);

    switch ($arg_count) {
      case 2:
        $fieldset = NULL;
        $key = $args[0];
        $item = $args[1];
        break;
      case 3:
        $fieldset = $args[0];
        $key = $args[1];
        $item = $args[2];
        break;
    }

    if (is_string($item)) {
      $item = new FormUIMarkup($item);
    }

    if ($this->weight !== NULL) {
      $item->setOption('weight', $this->weight);
      $this->incrementWeight();
    }

    $this->items[$key] = $item;
    if ($fieldset) {
      $this->items[$fieldset][$key] = $item;
      unset($this->items[$key]);
    }

    return $this;
  }

  /**
   * Add a fieldset
   */
  public function addFieldset($name, $options = array()) {
    $this->items[$name] = array('#type' => 'fieldset');
    foreach ($options as $option => $value) {
      $this->items[$name]['#' . $option] = $value;
    }
    return $this;
  }

  /**
   * Append a submit handler if it doesn't already exist.
   */
  public function addSubmitHandler($handler) {
    $this->prepareSubmitHandlers();

    $submit_handlers =& $this->items['#submit'];
    if (isset($this->items['actions']['submit'])) {
      $submit_handlers =& $this->items['actions']['submit']['#submit'];
    }

    // check that we're not adding redundant submit handlers
    if (in_array($handler, $submit_handlers)) {
      return $this;
    }

    array_push($submit_handlers, $handler);
    return $this;
  }

  /**
   * Append a validate handler if it doesn't already exist.
   */
  public function addValidateHandler($handler) {
    $this->prepareValidateHandlers();

    $validate_handlers =& $this->items['#validate'];
    if (isset($this->items['actions']['validate'])) {
      $validate_handlers =& $this->items['actions']['validate']['#validate'];
    }

    // check that we're not adding redundant validate handlers
    if (in_array($handler, $validate_handlers)) {
      return $this;
    }

    array_push($validate_handlers, $handler);
    return $this;
  }

  /**
   * Generate the Drupal compatible form API array
   */
  public function generate() {
    $form = array();
    foreach ($this->items as $key => $item) {
      if (is_array($item) && !$this->isOption($key)) {
        $form[$key] = array();
        foreach ($item as $item_key => $item_value) {
          // ignore #keys and $item_values that are arrays
          $form[$key][$item_key] = $item_value;
          if (!$this->isOption($item_key) && !is_array($item_value)) {
            $form[$key][$item_key] = $item_value->generate();
          }
        }
      }
      else {
        $form[$key] = $item;
        if (!$this->isOption($key)) {
          $form[$key] = $item->generate();
        }
      }
    }
    return $form;
  }

  /**
   * Is this thing a FAPI option
   *
   * @param string $key
   *   A string.
   *
   * @return bool
   *   TRUE if this is an option key
   */
  public function isOption($key) {
    return substr($key, 0, 1) === '#';
  }

  /**
   * Check if the item exists.
   *
   * @param string $key
   *   The item key to check.
   *
   * @return bool
   *   TRUE if the key exists, FALSE if not.
   */
  public function itemExists($key) {
    return isset($this->items[$key]);
  }

  /**
   * Increment the weight.
   */
  public function incrementWeight() {
    $this->weight += $this->weightIncrement;
    return $this;
  }

  /**
   * Make sure the form has submit handlers.
   *
   * Used internally, not chainable.
   */
  public function prepareSubmitHandlers() {
    if (!isset($this->items['actions']['submit']) && !isset($this->items['#submit'])) {
      $this->items['#submit'] = array();
    }
  }

  /**
   * Insert a submit handler at the start of the list
   */
  public function prependSubmitHandler($handler) {
    $this->prepareSubmitHandlers();

    $submit_handlers =& $this->items['#submit'];
    if (isset($this->items['actions']['submit'])) {
      $submit_handlers =& $this->items['actions']['submit']['#submit'];
    }

    array_unshift($handler, $submit_handlers);
    return $this;
  }

  /**
   * Prepare the validate handlers.
   */
  public function prepareValidateHandlers() {
    if (!isset($this->items['actions']['validate']) && !isset($this->items['#validate'])) {
      $this->items['#validate'] = array();
    }
  }

  /**
   * Set an existing item's options.
   *
   * @param string $item
   *   The item array key. This can also be a period-separated list, ex.
   *   'items.item'.
   * @param string $option
   *   The option to set.
   * @param mixed $value
   *   The option value.
   */
  public function set($item, $option, $value) {
    $parts = explode('.', $item);
    $this_item =& $this->items;
    foreach ($parts as $part) {
      if (!isset($this_item[$part])) {
        return $this;
      }
      $this_item =& $this_item[$part];
    }
    $this_item[$option] = $value;
    return $this;
  }

  /**
   * Set a form option
   */
  public function setOption($option, $value) {
    $option = '#' . $option;
    $this->items[$option] = $value;
    return $this;
  }

  /**
   * Set multiple options
   */
  public function setOptions($options) {
    foreach ($options as $option => $value) {
      $this->setOption($option, $value);
    }
    return $this;
  }

  /**
   * Set the weight.
   */
  public function setWeight($weight) {
    $this->weight = $weight;
    return $this;
  }

}
